### ISSUE TITLE
use different symbols for syllable divider and maqaf

### ISSUE THREAD

**Issue by bdenckla** [bdenckla/phonetic-hbo#25]
Perhaps keep using hyphen for maqaf but start using mid-dot for syllable divider.

**Comment by bdenckla** [comment]
I recently made a small step in this direction by using slash not dash when the same sound-code (one or two letters) is on both sides of a _maqaf_.

**Comment by skadish1** [comment]
Highly suggest using a double-dash for maqaph (including grey maqaph) and dropping the slash.

**Comment by bdenckla** [comment]
@skadish1 so from the above I see that for syllable divider and maqaf, you prefer number 1 below to number 2:

1. 1-dash and 2-dash: pen--na-MUT
2. 1-dash and slash: pen/na-MUT

I.e. you prefer 1-dash and 2-dash to 1-dash and slash. What's your "take" (if any) on the other alternatives such as:

![image](https://github.com/user-attachments/assets/c7f19769-3365-4d34-bb9b-51483507cb36)
![image](https://github.com/user-attachments/assets/96a3f3b9-2ce7-4db4-9e31-5c63f74aee7f)

- 1-dash and en-dash 
- mid-dot and 1-dash

These options are mentioned in [this B-Hebrew disscussion](http://bhebrew.biblicalhumanities.org/viewtopic.php?p=34171#p34171).

**Comment by skadish1** [comment]
The second one looks much better.
To the best of my recollection it is also more conventional.

**Comment by bdenckla** [comment]
Okay I took the plunge and made the following two big changes:

* Use dash for the atom divider (maqaf), unconditionally. (Formerly, it was dash (the same as the syllable divider) unless it was surrounded by the same sound. In that (somewhat rare) case, it was slash.)
* Made the syllable divider a middle dot.

Example:

![image](https://github.com/user-attachments/assets/8ac0c8ae-fdc7-41e9-bee3-5da0a0fea0c8)

**Comment by skadish1** [comment]
Looks good!
