### ISSUE TITLE
scrutinize qamats qatan in 1S24:10 לַהֲרׇגְﬞךָ֖

### ISSUE THREAD

**Issue by bdenckla** [bdenckla/phonetic-hbo#73]

**Comment by bdenckla** [comment]
Hm, maybe 1S24:10 לַהֲרׇגְﬞךָ֖ isn't such an outlier. I find a few others that are perhaps analogous. They involve _qamats qatan_ followed by a simple shewa that AHT judges to be vocal.

N | bcv | he | jta | X
--- | --- | --- | --- | ----
1 | [N33:34](https://bdenckla.github.io/MAM-with-doc/A4-Numbers.html#c33v34) | מִיׇּטְבָ֑תָה | miy.yo.t^.!va.ta | ט
2 | [Je5:6](https://bdenckla.github.io/MAM-with-doc/C2-Jeremiah.html#c5v6) | יְשׇׁדְדֵ֔ם | y^.sho.d^.!dEm | ד
3 | [Ps86:2](https://bdenckla.github.io/MAM-with-doc/D1-Psalms.html#c86v2) | שׇׁ֥מְרָ֣ה | sho.m^.!ra | מ
4 | [Song7:3](https://bdenckla.github.io/MAM-with-doc/E1-Song%20of%20Songs.html#c7v3) | שׇׁרְ֯רֵךְ֙ | sho.r^.!rEkh | ר

(X = _shewa_ on letter X is vocal according to AHT)

Misc. notes:

- 2 of these 4 involve a pair of identical letters separated by simple _shewa_, a case that is sometimes treated specially. 
- Song7:3 שׇׁרְ֯רֵךְ֙ involves not only a pair of identical letters, but also that letter is *resh*, and simple *shewa* on _resh_ is sometimes treated specially.
- N33:34 מִיׇּטְבָ֑תָה is regular but not even "almost fully regular." I guess you could just call that plain old regular. It isn't FR3 because its _shewa_ right before the stress is not a _ḥaṭef_. And it isn't AFR3 because its buffer syllable's vowel, a _qamats qatan_, is not a long vowel.
- Ps86:2 שׇׁ֥מְרָ֣ה is one of those "does this poetic _merkha_ imply any stress?" cases. I'm not sure what difference it would make if it did or did not imply any stress. Anyway, this _qamats qatan_ is documented in MAM (see below) so I assume it is quite intentional.

MAM's documentation for Ps86:2 שׇׁ֥מְרָ֣ה:

> לפי ויינברג, 3.2.2.3; חנן אריאל, על סימון השוואים והקמצים, עמ' 3-5 ובמיוחד בהערה 26 שם. וראו עוד בפירושי ראב"ע ורד״ק.

**Comment by skadish1** [comment]
All four of them are correct. Koren agrees in all places. Simanim goes Sephardic as expected for Psalms 86:2 (merkha must mean a long vowel), and then weirdly in the two cases of shewa between identical letters marks a vocal shewa and also marks qamaz qatan (!).
Yotvata is from Weinberg (3.7.1. b. page 165). I have no idea why Hillel has it that way (it should be corrected at AlHatorah).
In the two cases of shewa between identical letters, Hillel's program probably marked it is שווא נע automatically, even though both are cases of a double-ע root. They appear in Weinberg 3.1.1 and 3.4 n. 37.

**Comment by bdenckla** [comment]
Thanks @skadish1. So, it sounds like you would advise interpreting the simple *sheva* of all four cases as silent. Correct?

BTW I don't think it is relevant, but I noticed that Koren has merely _gaʿya_ not _merkha_ on Ps86:2 שׇׁ֥מְרָ֣ה.

**Comment by skadish1** [comment]
Correct.
Regarding Koren, that is typical and expected.

**Comment by bdenckla** [comment]
Sorry, one more clarification: do you advise interpreting the simple *shewa* as silent in both the ד and ס variants of שמרה, i.e. both ד=שׇׁ֥מְרָ֣ה and ס=שָׁ֥מְרָ֣ה? Or only in ד=שׇׁ֥מְרָ֣ה?

**Comment by skadish1** [comment]
No! Whenever there is ס=, i.e. the Sephardic vocalization, it interprets
the ga`ya or the merkha to mean that the qamaz is a long vowel and the
following shewa is heard (שווא נע).
So only in ד= is it שווא נח.

**Comment by bdenckla** [comment]
> Whenever there is ס=, i.e. the Sephardic vocalization, it interprets the ga`ya or the merkha to mean that the qamaz is a long vowel and the following shewa is heard (שווא נע). So only in ד= is it שווא נח.

Okay that makes sense to me, thanks.

**Comment by bdenckla** [comment]
Done. See [Avi's change on Wikisource](https://he.wikisource.org/w/index.php?title=%D7%A9%D7%9E%D7%95%D7%90%D7%9C_%D7%90_%D7%9B%D7%93%2F%D7%98%D7%A2%D7%9E%D7%99%D7%9D&diff=2888500&oldid=2860338).
